# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gradient of the logistic regression risk.
#'
#' Computes the gradient of the logistic regression error: \deqn{f(x) = 1/n
#' sum_{i=1}^n ( log(1 + exp(- b_i * x' * A_i) ) ,} for a given design matrix
#' \code{A} and a response binary vector \code{b} with values \code{+1} and
#' \code{-1}.
#'
#' @param x A p-dimensional vector where the gradient is computed.
#' @param opts List of parameters, which must include: \itemize{ \item \code{A},
#'   a n*p design matrix \item \code{b}, a n-dimensional response vector taking
#'   values \eqn{1} or \eqn{-1}. }
#'
#' @return The gradient of the function \eqn{f(x) = 1/n sum_{i=1}^n ( log(1 +
#'   exp(- b_i * x' * A_i) )}, which is: \deqn{f'(x) = 1/n sum_{i=1}^n -b_i A_i
#'   / (1 + exp( b_i * x' * A_i ))}
#'
#' @export
#' @examples grad.logistic(c(1,3,-2), list(A=diag(3), b=c(1,-1,1))
#' # The following give the same (elastic net penalized logistic regression without offset):
#' glmnet(A,b,family="binomial",lambda=0.1,standardize=FALSE,intercept=FALSE, alpha=0.5)$b
#' apg(grad.logistic, prox.elasticnet, ncol(A), list(A=A, b=b, lambda=0.1, alpha=0.5) )$x
#' 
grad_logistic <- function(x, opts) {
    .Call('_apg_grad_logistic', PACKAGE = 'apg', x, opts)
}

#' @useDynLib apg
#' @importFrom Rcpp sourceCpp
NULL

#' Gradient of the ranking logistic regression risk.
#'
#' Computes the gradient of the ranking logistic regression error: \deqn{f(x) = 1/|comp|
#' sum_{(i,j)\in comp} ( log(1 + exp(- x' * (A_j - A_i) )} for a given design matrix
#' \code{A} and a set of pairs \eqn{(i,j)\in P} where the j-th sample is larger than the i-th sample.
#'
#' @param x A p-dimensional vector where the gradient is computed.
#' @param opts List of parameters, which must include: \itemize{ \item \code{A},
#'   a n*p design matrix \item \code{comp}, a list of length n, where the i-th entry is a vector containing the indices of the samples j which are larger than sample i.}
#'
#' @return The gradient of the function \eqn{f(x) = 1/|comp|
#' sum_{(i,j)\in comp} ( log(1 + exp(- x' * (A_j - A_i) )}, which is: \deqn{f'(x) = 1/|comp| sum_{(i,j)\in comp} (A_j - A_i) / (1 + exp( x' * ( A_i - A_j) )}
#'
#' @export
#' @examples grad.rankinglogistic(c(1,3,-2), list(A=diag(3), comp=list(as.integer(c(2,3)),as.integer(3),integer(length=0))))
grad.rankinglogistic <- function(x, opts) {
    .Call('_apg_grad_ranking_logistic', PACKAGE = 'apg', x, opts)
}

